### ISSUE TITLE
[JENKINS-65650] java.lang.NoClassDefFoundError: org/junit/rules/ExternalResource on builds after upgrade to 2.277.4 

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/gerrit-trigger-plugin#930]
<p> </p>

<p>For every build since upgrading from 2.277.2 to 2.277.4 Jenkins appears to work fine, but throws frequently the following traceback in the logs:</p>

<p> </p>

```
2021-05-16 22:00:00.601+0000 [id=109937]WARNINGh.model.listeners.RunListener#report: RunListener failed
java.lang.NoClassDefFoundError: org/junit/rules/ExternalResource
at org.jvnet.hudson.test.BuildWatcher$Listener.onStarted(BuildWatcher.java:89)
at hudson.model.listeners.RunListener.fireStarted(RunListener.java:238)
at hudson.model.Run.execute(Run.java:1905)
at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
at hudson.model.ResourceController.execute(ResourceController.java:97)
at hudson.model.Executor.run(Executor.java:429)   

2021-05-16 22:00:07.018+0000 [id=109937]WARNINGh.model.listeners.RunListener#report: RunListener failed
java.lang.NoClassDefFoundError: org/junit/rules/ExternalResource
at org.jvnet.hudson.test.BuildWatcher$Listener.onFinalized(BuildWatcher.java:100)
at hudson.model.listeners.RunListener.fireFinalized(RunListener.java:255)
at hudson.model.Run.onEndBuilding(Run.java:2069)  
at hudson.model.Run.execute(Run.java:1976)
at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
at hudson.model.ResourceController.execute(Resource~   
```
<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/rikuvoipio.svg" title="rikuvoipio's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rikuvoipio">rikuvoipio</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-65650" target="_blank">java.lang.NoClassDefFoundError: org/junit/rules/ExternalResource on builds after upgrade to 2.277.4 </a></i></summary>
<i><ul>
<li><b>status</b>: Fixed but Unreleased
<li><b>priority</b>: Minor
<li><b>component(s)</b>: gerrit-trigger-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2021-07-15T17:56:58+00:00
<li><b>votes</b>: 2
<li><b>watchers</b>: 12
<li><b>imported</b>: 2025-12-07
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p> </p>

<p>For every build since upgrading from 2.277.2 to 2.277.4 Jenkins appears to work fine, but throws frequently the following traceback in the logs:</p>

<p> </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2021-05-16 22:00:00.601+0000 [id=109937]        WARNING        h.model.listeners.RunListener#report: RunListener failed
java.lang.NoClassDefFoundError: org/junit/rules/ExternalResource
        at org.jvnet.hudson.test.BuildWatcher$Listener.onStarted(BuildWatcher.java:89)
        at hudson.model.listeners.RunListener.fireStarted(RunListener.java:238)
        at hudson.model.Run.execute(Run.java:1905)        
        at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:429)   

2021-05-16 22:00:07.018+0000 [id=109937]        WARNING        h.model.listeners.RunListener#report: RunListener failed
java.lang.NoClassDefFoundError: org/junit/rules/ExternalResource
        at org.jvnet.hudson.test.BuildWatcher$Listener.onFinalized(BuildWatcher.java:100)
        at hudson.model.listeners.RunListener.fireFinalized(RunListener.java:255)
        at hudson.model.Run.onEndBuilding(Run.java:2069)  
        at hudson.model.Run.execute(Run.java:1976)        
        at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
        at hudson.model.ResourceController.execute(Resource~   </pre>
</div></div>
<p> </p>

<p> </p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>jenkins/jenkins:2.277.4-lts-slim docker image<br/></code></li></ul>
